return {
    name = "KryptDbg",
    version = "1.5.0",
    ui = "src/KryptUI.lua",
    core = "src/Runtime.lua",
    defaultFeature = "Explorer",
    features = {
        {
            id = "Explorer",
            icon = "folder-tree",
            title = "Explorer",
            description = "Instances and properties",
            path = "src/features/Explorer.lua",
            shortcut = Enum.KeyCode.One,
        },
        {
            id = "Remotes",
            icon = "radio",
            title = "Remotes",
            description = "Remote traffic",
            path = "src/features/Remotes.lua",
            shortcut = Enum.KeyCode.Two,
        },
        {
            id = "Scripts",
            icon = "file-code-2",
            title = "Scripts",
            description = "Script index and source",
            path = "src/features/Scripts.lua",
            shortcut = Enum.KeyCode.Three,
        },
        {
            id = "Console",
            icon = "square-terminal",
            title = "Console",
            description = "Output and commands",
            path = "src/features/Console.lua",
            shortcut = Enum.KeyCode.Four,
        },
        {
            id = "Diagnostics",
            icon = "activity",
            title = "Diagnostics",
            description = "Runtime health",
            path = "src/features/Diagnostics.lua",
            shortcut = Enum.KeyCode.Five,
        },
        {
            id = "Settings",
            icon = "cog",
            title = "Settings",
            description = "Preferences and AI dump",
            path = "src/features/Settings.lua",
            shortcut = Enum.KeyCode.Six,
        },
    },
}
