return {
    name = "KryptDbg",
    version = "1.0.0",
    ui = "src/KryptUI.lua",
    core = "src/Runtime.lua",
    defaultFeature = "Explorer",
    features = {
        {
            id = "Explorer",
            icon = "EX",
            title = "Explorer",
            description = "Instances and properties",
            path = "src/features/Explorer.lua",
            shortcut = Enum.KeyCode.One,
        },
        {
            id = "Remotes",
            icon = "RX",
            title = "Remotes",
            description = "Remote traffic",
            path = "src/features/Remotes.lua",
            shortcut = Enum.KeyCode.Two,
        },
        {
            id = "Scripts",
            icon = "SC",
            title = "Scripts",
            description = "Script index and source",
            path = "src/features/Scripts.lua",
            shortcut = Enum.KeyCode.Three,
        },
        {
            id = "Console",
            icon = "OUT",
            title = "Console",
            description = "Output and commands",
            path = "src/features/Console.lua",
            shortcut = Enum.KeyCode.Four,
        },
        {
            id = "Diagnostics",
            icon = "DX",
            title = "Diagnostics",
            description = "Runtime health",
            path = "src/features/Diagnostics.lua",
            shortcut = Enum.KeyCode.Five,
        },
    },
}
